### ISSUE TITLE
When will you release the open-source version of it?

### ISSUE THREAD

**Issue by Zero3K** [0xda568/Universal-Watermark-Disabler-Reverse-Engineering#1]
*subject*

**Comment by 0xda568** [comment]
Hi, I kinda pushed the project to the side, but I think this is a great reminder to finish what I started. It should be ready to go in the next couple of days.

**Comment by Zero3K** [comment]
1. Will it be smaller in file size than the current one?
2. Will it be able to remove the watermark shown in Windows 7 and below?

**Comment by 0xda568** [comment]
At least for the first release, I am not planning to make it backwards compatible. So it should be able to support Windows 10 & 11 x64.

Regarding the size, I would say that a simple batch script is enough for the installation / removal of the needed files. So I should be able to save some bytes by removing the GUI :)

**Comment by Zero3K** [comment]
Why was this closed?

**Comment by upiter** [comment]
> Why was this closed?

Open source alternative to the Universal Watermark Remover [released](https://github.com/0xda568/uwd-oss).
