### ISSUE TITLE
reverse source

### ISSUE THREAD

**Issue by pr701** [0xda568/Universal-Watermark-Disabler-Reverse-Engineering#2]
Thanks for the great article.
This proxy dll was written by me back in 2015, I was surprised to see it being used.
I will try to find the source code and post it later on git with a link to this article =)

Now, this dll is likely to cause problems on modern versions of Windows.
Ps It's also not compatible with StartIsBack

**Comment by 0xda568** [comment]
Wow, huge honor to have you here! It still does its job on the newest versions of win10, haven't tested it yet on win11 :)

**Comment by pr701** [comment]
Done
https://github.com/pr701/universal-watermark-disabler
